#' Translate PSEA results for Mass Spectrometry searching tools
#'
#' @param x A list of psea results generated by `runPSEA` function.
#' @param sig.level The significance level to filter PTMs (applies on adjusted p-value). Default value is 0.05
#' @param number.rep Only consider PTM terms that occurred more than a specific number of times in UniProt. This number is set
#' by number.rep parameter. The default value is NULL.
#' @export
#'
#' @import stringr
#'
#' @examples
#' psea_res <- runPSEA(protein = exmplData2, os.name = 'Rattus norvegicus (Rat)', nperm = 100)
#' MS <- psea2mass(x = psea_res, sig.level = 0.05)
psea2mass = function(x, sig.level = 0.05, number.rep = NULL){

  temp    <- x[[1]] %>% filter( (nMoreExtreme / x[[6]]) <= sig.level )

  if( !is.null(number.rep) ){
    temp <- temp %>% filter(FreqinUniProt >= number.rep)
  }

  temp <- temp %>% arrange('FreqinList')

  pathway <- as.character(temp$PTM)

  # look up each pathway in https://www.uniprot.org/docs/ptmlist.txt
  temp    <- ptmlist %>% filter( ID %in% pathway )
  DR      <- temp$DR


  # print name field from https://raw.githubusercontent.com/HUPO-PSI/psi-mod-CV/master/PSI-MOD.obo
  res <- mod_ont %>% filter(id %in% DR)

  # Remove part of the definition column
  res$def <- str_replace(string = res$def, pattern = 'A protein modification that effectively ', replacement = '')

  return(res)
}




